# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"

#logo-facebook = "https://facebook.com/"
logo-twitter = "https://twitter.com/jospaquim"
#logo-instagram = "https://instagram.com/"
logo-linkedin = "https://www.linkedin.com/in/jospaquim"
logo-github = "https://github.com/jospaquim"
#logo-dribbble = "https://dribbble.com/"
# logo-figma = "figma.com/"
# logo-youtube = "https://youtube.com/"
# logo-reddit = "https://www.reddit.com/"
# logo-discord = "https://discord.com/"
# logo-pinterest = "https://www.pinterest.com/"